// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDifJ9RksTpFmoimx4tIBMUCktiHN4_YnU',
    appId: '1:647140541459:web:316925efca4ec7d1572be6',
    messagingSenderId: '647140541459',
    projectId: 'flutter-ibalik',
    authDomain: 'flutter-ibalik.firebaseapp.com',
    storageBucket: 'flutter-ibalik.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqi3cD6aEXjyycbwtp9k3hAoL6VPn3oTg',
    appId: '1:647140541459:android:22adef3a8b03192d572be6',
    messagingSenderId: '647140541459',
    projectId: 'flutter-ibalik',
    storageBucket: 'flutter-ibalik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwqcGG5-_LMBKG7ydPoi37seQvIjvwLRA',
    appId: '1:647140541459:ios:a1eca9e02a3858ac572be6',
    messagingSenderId: '647140541459',
    projectId: 'flutter-ibalik',
    storageBucket: 'flutter-ibalik.firebasestorage.app',
    iosBundleId: 'com.example.flutterIbalik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwqcGG5-_LMBKG7ydPoi37seQvIjvwLRA',
    appId: '1:647140541459:ios:a1eca9e02a3858ac572be6',
    messagingSenderId: '647140541459',
    projectId: 'flutter-ibalik',
    storageBucket: 'flutter-ibalik.firebasestorage.app',
    iosBundleId: 'com.example.flutterIbalik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDifJ9RksTpFmoimx4tIBMUCktiHN4_YnU',
    appId: '1:647140541459:web:a5529a1f62846cd9572be6',
    messagingSenderId: '647140541459',
    projectId: 'flutter-ibalik',
    authDomain: 'flutter-ibalik.firebaseapp.com',
    storageBucket: 'flutter-ibalik.firebasestorage.app',
  );
}
